# Generated by Django 3.0.8 on 2020-12-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountPeriod',
        ),
    ]
