# Generated by Django 3.0.8 on 2020-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='budgetEject',
            field=models.BigIntegerField(null=True),
        ),
    ]
