# Generated by Django 3.0.8 on 2020-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='vouchePayment',
            field=models.BigIntegerField(null=True),
        ),
    ]
