# Generated by Django 3.0.8 on 2020-12-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_remove_account_accountperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountPeriod',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='budgets.AccountPeriod'),
            preserve_default=False,
        ),
    ]
