# Generated by Django 3.0.8 on 2020-12-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_discountmovement_movementacount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmovement',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Movement'),
        ),
    ]
