# Generated by Django 3.0.8 on 2020-09-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_movement_typeagreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='codeAg',
        ),
    ]
