# Generated by Django 3.0.8 on 2020-11-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_movement_vouchepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMovement', models.CharField(max_length=100)),
                ('RightsEconomic', models.BooleanField()),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Movement')),
                ('third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Third')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypeRubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAccount', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('bussines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Bussines')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Rubro')),
            ],
        ),
    ]
