# Generated by Django 3.0.8 on 2020-11-02 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_accounttyperubro_informationmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttyperubro',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Account'),
        ),
    ]
