# Generated by Django 3.0.8 on 2020-09-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_agreement_codeag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='typeAgreement',
        ),
        migrations.AddField(
            model_name='movement',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Agreement'),
        ),
    ]
