# Generated by Django 3.0.8 on 2020-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_accounttyperubro_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttyperubro',
            name='value',
            field=models.BigIntegerField(null=True),
        ),
    ]
