# Generated by Django 3.0.8 on 2020-11-04 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_accounttyperubro_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttyperubro',
            name='value',
        ),
        migrations.CreateModel(
            name='ValuesAccountObligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAccount', models.CharField(max_length=100)),
                ('value', models.BigIntegerField(null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Account')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.RubroMovement')),
            ],
        ),
    ]
