# Generated by Django 3.0.8 on 2020-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_agreement_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='numberAg',
            field=models.CharField(max_length=100),
        ),
    ]
