# Generated by Django 3.0.8 on 2020-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20201007_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='contraOperarName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
