# Generated by Django 3.0.8 on 2020-11-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20201103_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesaccountobligation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.AccountTypeRubro'),
        ),
    ]
